In [1]:
import pybitClass as pc 
import pandas as pd
c = pc.BybitAPI()

In [39]:
c.account_info()

,marginMode,updatedTime,unifiedMarginStatus,dcpStatus,timeWindow,smpGroup,isMasterTrader,spotHedgingStatus
0,REGULAR_MARGIN,0,1,OFF,10,0,False,OFF

In [40]:
c.asset_info('USDT')

[]

In [41]:
# c.cancel_order()

In [42]:
c.coin_info('BTCUSDT')

,symbol,contractType,status,baseCoin,quoteCoin,launchTime,deliveryTime,deliveryFeeRate,priceScale,leverageFilter,priceFilter,lotSizeFilter,unifiedMarginTrade,fundingInterval,settleCoin,copyTrading,upperFundingRate,lowerFundingRate
0,BTCUSDT,LinearPerpetual,Trading,BTC,USDT,1584230400000,0,,2,"{'minLeverage': '1', 'maxLeverage': '100.00', 'leverageStep': '0.01'}","{'minPrice': '0.10', 'maxPrice': '199999.80', 'tickSize': '0.10'}","{'maxOrderQty': '1190.000', 'minOrderQty': '0.001', 'qtyStep': '0.001', 'postOnlyMaxOrderQty': '1190.000', 'maxMktOrderQty': '119.000', 'minNotionalValue': '5'}",True,480,USDT,both,0.00375,-0.00375

In [39]:
c.klines('BTCUSDT',60,10,)

,date,open,high,low,close,volume,turnover
0,2024-04-30 16:58:59.968,60304.9,60422.0,60169.3,60379.9,431.826,2.603055e+07
1,2024-04-30 16:00:01.024,60760.0,60879.1,60121.0,60304.9,13506.084,8.163695e+08
2,2024-04-30 15:01:02.080,61211.5,61365.0,60545.0,60760.0,10130.675,6.167449e+08
3,2024-04-30 13:59:52.064,60800.1,61554.6,60500.8,61211.5,15188.315,9.265514e+08
4,2024-04-30 13:00:53.120,61214.9,61289.7,60748.6,60800.1,7152.109,4.366966e+08
5,2024-04-30 11:59:43.104,61194.5,61328.9,60703.0,61214.9,10697.814,6.533003e+08
6,2024-04-30 11:00:44.160,61754.3,61754.4,61001.7,61194.5,12001.738,7.356860e+08
7,2024-04-30 09:59:34.144,61645.5,61760.3,61350.0,61754.3,7447.350,4.588254e+08
8,2024-04-30 09:00:35.200,61878.5,62080.0,61515.0,61645.5,11572.347,7.155229e+08
9,2024-04-30 07:59:25.184,63114.8,63209.0,61757.0,61878.5,17296.244,1.079127e+09

In [44]:
# c.order()

In [2]:
posi = c.position_info(settleCoin = 'USDT')

In [3]:
posi

,positionIdx,riskId,riskLimitValue,symbol,side,size,avgPrice,positionValue,tradeMode,positionStatus,autoAddMargin,adlRankIndicator,leverage,positionBalance,markPrice,liqPrice,bustPrice,positionMM,positionIM,tpslMode,takeProfit,stopLoss,trailingStop,unrealisedPnl,cumRealisedPnl,curRealisedPnl,seq,isReduceOnly,mmrSysUpdatedTime,leverageSysUpdatedTime,sessionAvgPrice,createdTime,updatedTime
0,0.0,1.0,200000.0,OPUSDT,Sell,66.2,2.526,167.2212,1.0,Normal,0.0,2.0,15.0,11.246184,2.57,2.6691,2.6944,1.783693,3.344424,Full,2.4518,0.0,0.0,-2.9128,-3.417206,-0.016618,1.334117e+11,False,,,,1.714568e+12,1.714579e+12

In [4]:
entry = posi['avgPrice']
mark = posi['markPrice']
leverage = posi['leverage']
# side =  1 if posi['side'] =='Buy' else -1 

-round((((mark-entry)/mark)*100*leverage),2)

0   -25.68
dtype: float64

In [11]:
import pandas as pd
import random

# 데이터 생성
data = {'side': ['Buy', 'Sell', 'Buy', 'Buy', 'Sell'],
        'pnl': [random.randint(0, 100) for _ in range(5)]}

# 데이터프레임 생성
df = pd.DataFrame(data)

# side가 'Sell'인 경우 pnl에 -를 붙이기
df.loc[df['side'] == 'Sell', 'pnl'] = -df.loc[df['side'] == 'Sell', 'pnl']

df

   side  pnl
0   Buy    9
1  Sell  -55
2   Buy   45
3   Buy   30
4  Sell    0

In [46]:
try:
	c.set_leverage('BTCUSDT',10)
except:
    pass

In [47]:
try:
	c.set_marginType('STEEMUSDT', 1, 10)
except:
    pass

In [48]:
# c.traiding_stop()

In [49]:
c.wallet()

,coin,equity,usdValue,walletBalance,borrowAmount,availableToBorrow,availableToWithdraw,accruedInterest,totalOrderIM,totalPositionIM,totalPositionMM,unrealisedPnl,cumRealisedPnl
0,BTC,0,,0,,,0,,0,0,,0,0

In [38]:
df = c.all_tickers().sort_values('price24hPcnt', ascending=False).reset_index(drop = True)
df[df['turnover24h']>4e+06].reset_index(drop = True)

,symbol,lastPrice,indexPrice,markPrice,prevPrice24h,price24hPcnt,highPrice24h,lowPrice24h,prevPrice1h,openInterest,openInterestValue,turnover24h,volume24h,fundingRate,nextFundingTime,predictedDeliveryPrice,basisRate,deliveryFeeRate,deliveryTime,ask1Size,bid1Price,ask1Price,bid1Size,basis
0,ZETAUSDT,1.196900,1.198500,1.197200,1.147000,0.043504,1.263400,1.143000,1.176200,6.565420e+06,7860120.82,3.253038e+07,2.700474e+07,0.000015,1.714522e+12,,,,0.0,68.00,1.196700,1.197500,184.00,
1,STEEMUSDT,0.281400,0.281900,0.281400,0.271800,0.035320,0.298500,0.266100,0.280600,8.990759e+06,2529999.58,2.181853e+07,7.697277e+07,-0.000489,1.714522e+12,,,,0.0,3140.00,0.281200,0.281300,371.00,
2,JTOUSDT,3.079000,3.083000,3.080000,2.988000,0.030455,3.276000,2.933000,3.035000,3.285680e+06,10119894.40,4.139455e+07,1.335120e+07,0.000002,1.714522e+12,,,,0.0,668.10,3.079000,3.080000,8.70,
3,LEVERUSDT,0.002887,0.002889,0.002887,0.002855,0.011208,0.003282,0.002827,0.002914,1.417930e+09,4093563.91,5.446851e+07,1.771451e+10,0.000100,1.714522e+12,,,,0.0,606900.00,0.002886,0.002889,926400.00,
4,GALUSDT,3.459300,3.460400,3.459300,3.425900,0.009749,3.575500,3.307600,3.462900,1.833461e+06,6342491.64,4.138176e+07,1.201399e+07,0.000081,1.714522e+12,,,,0.0,29.91,3.458800,3.459700,5.99,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,ORDIUSDT,34.276000,34.337000,34.298000,40.688000,-0.157589,43.170000,33.401000,35.408000,7.297680e+05,25029583.89,1.065225e+08,2.787890e+06,0.000100,1.714522e+12,,,,0.0,20.17,34.273000,34.274000,0.28,
163,DEGENUSDT,0.019610,0.019590,0.019600,0.023340,-0.159811,0.025070,0.019020,0.019660,5.634952e+08,11044506.31,3.118290e+07,1.449224e+09,0.000100,1.714522e+12,,,,0.0,145530.00,0.019610,0.019630,12510.00,
164,ORNUSDT,1.437000,1.441000,1.438000,1.731000,-0.169844,1.734000,1.403000,1.468000,6.954027e+05,999989.08,4.286375e+06,2.694393e+06,0.000066,1.714522e+12,,,,0.0,539.30,1.436000,1.437000,119.90,
165,SAFEUSDT,1.761600,1.762100,1.761600,2.132100,-0.173772,2.158900,1.673600,1.728900,1.099880e+06,1937548.08,3.352427e+07,1.733411e+07,0.000100,1.714522e+12,,,,0.0,9.00,1.760200,1.761500,9.00,
166,PENDLEUSDT,4.169300,4.174600,4.170900,5.176800,-0.194618,5.218800,4.151200,4.251100,4.021906e+06,16774967.74,1.629311e+08,3.520092e+07,0.000100,1.714522e+12,,,,0.0,338.00,4.168900,4.169400,53.00,

In [24]:
4e+06

4000000.0